### ISSUE TITLE
Error on removal of package containing treeware/plant

### ISSUE THREAD

**Issue by jamesmills** [TreewareEarth/plant#3]
I've tested an installed remove and I got this on the remove

```
 jamesmills@Jamess-MacBook-Pro-2  ~/Projects/Packages/example-app  composer remove jamesmills/laravel-timezone                                                                                              
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 3 removals
  - Removing treeware/plant (dev-main)
  - Removing torann/geoip (3.0.2)
  - Removing jamesmills/laravel-timezone (dev-master)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/sail
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
PHP Fatal error:  Uncaught Error: Class 'Treeware\Plant\PackageRepo' not found in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code:74
Stack trace:
#0 [internal function]: Treeware\Plant\Plugin_composer_tmp0->showBanner(Object(Composer\Script\Event))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(323): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', true)
#4 phar:///usr/local/bin/composer/src/Composer/Command/RemoveCommand.php(140): Composer\Installer->run()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(241): Composer\Command\RemoveCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Sy in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 74

Fatal error: Uncaught Error: Class 'Treeware\Plant\PackageRepo' not found in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code:74
Stack trace:
#0 [internal function]: Treeware\Plant\Plugin_composer_tmp0->showBanner(Object(Composer\Script\Event))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(323): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', true)
#4 phar:///usr/local/bin/composer/src/Composer/Command/RemoveCommand.php(140): Composer\Installer->run()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(241): Composer\Command\RemoveCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Sy in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 74
```

**Comment by ostark** [comment]
Thanks!

**Comment by ostark** [comment]
WOW! You are using Composer < 1.10.0. 
Others might do as well.

**Comment by ostark** [comment]
Hopefully solved https://github.com/TreewareEarth/plant/commit/a0dc5b138111eac89dde961d008700b973481127
